### ISSUE TITLE
Having classpath issue with gradle version 3.4

### ISSUE THREAD

**Issue by pierrelucveilleux** [ratpack/ratpack#1173]
Classpath does not seems right when I upgrade gradle to version 3.4. I had no issues with 3.3

ratpack gradle = io.ratpack:ratpack-gradle:1.4.5

When I run my application from IntelliJ I got java.lang.NoClassDefFoundError even if it appears in project dependencies. Run command does not add any gradle dependencies.

I had no problem upgrading to gradle 3.4.1 with project not using ratpack.

**Comment by SlyDen** [comment]
Try run app in terminal with gradle ... 
I noticed issues after IDEA upgrade to 2016.3.4 (CE) ... can't confirm it is the reason, but
I have problems with running my project in IDEA (debug mode as well), e.g.:
`Exception in thread "main" java.lang.NoClassDefFoundError: ratpack/handling/Handler`

For `ratpack.groovy` I've got Multiple compilation etc. (I rewrote start class to plain Java since then).

The workaround (actually it is better solution I managed to complete at last with no excuses about time :) )
 
1) configured Gradle run task  to start java with remote debugging (triggered by ENV var, as well as profile with specific ENV vars for staging, dev etc.)

2) run IDEA with remote debug profile for development (overwise don't care ...)

BONUS: I'm running gradle with `-t` flag and have continuos recompilation on file changes + `build-notification` in the tray ...

**Comment by alkemist** [comment]
This is actually an IDEA bug. You can get around it by unticking “Create a module for each source set“ in IDEA's Gradle prefs.

**Comment by pierrelucveilleux** [comment]
Thanks

Le ven. 10 mars 2017 à 16:00, Luke Daley <notifications@github.com> a
écrit :
