### ISSUE TITLE
Memory leak with Ratpack's Promise trampoline

### ISSUE THREAD

**Issue by jeff-blaisdell** [ratpack/ratpack#1300]
### Problem
Often times it is necessary to perform an iterable action indefinitely for things such as long polling an external queue.  Ratpack provides at least a couple ways to accomplish this in a non-blocking manner.  One mechanism is through Ratpack Promise's internal trampoline.  It allows you to infinitely recurse without accumulating stack causing an overflow.  The problem with this approach is that Ratpack appears to maintain references to objects created during each iteration which prevents GC.  The end result is heap memory exhaustion.

Created the following project to demonstrate issue:
https://github.com/jeff-blaisdell/ratpack-infinity

### Example 1
[InfinityRecursionAction](https://github.com/jeff-blaisdell/ratpack-infinity/blob/master/src/main/java/infinity/InfinityRecursionAction.java)

A Ratpack Action that upon execution recursively iterates consequently producing an Out of Memory exception.

### Example 2
[InfinityForkAction](https://github.com/jeff-blaisdell/ratpack-infinity/blob/master/src/main/java/infinity/InfinityForkAction.java)

A Ratpack Action that upon execution infinitely forks executions.  This performs as expected with memory allocated being appropriately GC'd after each iteration.

### Observed Behavior
Ran test on both Ratpack 1.4.5 and 1.5.1.  Problem appears in both versions of Ratpack, 1.5.1
appears to go a little longer before exhausting the heap.

#### Infinite Forked Executions 
Heap memory is properly cleared on each iteration.
[Download Heap Dump](https://drive.google.com/file/d/1TlJJ4VPUr0vDD1vUFce8IrlAdy_q_AcY/view?usp=sharing)
![Infinite Fork Heap](https://github.com/jeff-blaisdell/ratpack-infinity/blob/master/reports/ratpack-infinity-fork-heap.png?raw=true "Infinite Fork Heap")
![Infinite Recursion Leak Suspect](https://github.com/jeff-blaisdell/ratpack-infinity/blob/master/reports/ratpack-infinity-fork-leak-suspect.png?raw=true "Infinite Fork Leak Suspect")

#### Infinite Recursive Promises Executions
Heap memory is leaked on each iteration.  The expectation here is that the internal trampoline
of Ratpack's Promise should behave much like an iterable with the objects created and scoped within
the iteration becoming eligible for GC at the end of each iteration.
[Download Heap Dump](https://drive.google.com/file/d/1o39GYftb5R71hoEhfdDkwDilxOjyj_Qj/view?usp=sharing) 
![Infinite Recursion Heap](https://github.com/jeff-blaisdell/ratpack-infinity/blob/master/reports/ratpack-infinity-recursion-heap.png?raw=true "Infinite Recursion Heap")
![Infinite Recursion Leak Suspect](https://github.com/jeff-blaisdell/ratpack-infinity/blob/master/reports/ratpack-infinity-recursion-leak-suspect.png?raw=true "Infinite Recursion Leak Suspect")
![Infinite Recursion Dominator Tree](https://github.com/jeff-blaisdell/ratpack-infinity/blob/master/reports/ratpack-infinity-recursion-dominator-tree.png?raw=true "Infinite Recursion Dominator Tree")

**Comment by ldaley** [comment]
Thank you very much for the great analysis @jeff-blaisdell. I submitted a PR with a working version of the infinite action recursion here:  https://github.com/jeff-blaisdell/ratpack-infinity/pull/1

I can't see how to make your version work as is. The fundamental issue is that promises are reusable. So it needs to hold on to all of its upstream pipeline as it goes. Your version creates an infinitely long pipeline, which ends up exhausting heap. My version creates some pipeline, uses it and then throws it away, creates some pipeline etc. 

I've pondered this before, but so far I haven't been able to work out how to make this work. Some compilers make it work by actually detecting recursion. That's not practical for us as far as I can tell, because we don't have that same level of insight in to the code.

I'm going to optimistically close this issue. Please don't hesitate to reopen if you think there's more to do.
