### ISSUE TITLE
Proposal: Promise onComplete actions

### ISSUE THREAD

**Issue by drmaas** [ratpack/ratpack#1464]
Proposing to add a method to `Promise` to allow taking action on a promise when it completes without a value.

```
  default Promise<T> onComplete(Block block) {
    return transform(up -> down ->
      up.connect(down.onComplete(() -> {
        try {
          block.execute();
        } catch (Throwable e) {
          down.error(e);
        }
      }))
    );
  }
```

This would be useful in a chain where a Promise from a dependent library issued on `onError`, thus terminating the promise, and the user code wants to take action when a promise is terminated without a value. There might be other scenarios as well where a promise would terminate, and a user would want to execute and arbitrary block of code when that happens.

**Comment by johnrengelman** [comment]
You can consume an `ExecResult` from the `Promise` using `Promise.result` (https://github.com/ratpack/ratpack/blob/master/ratpack-exec/src/main/java/ratpack/exec/Promise.java#L469-L498) which will tell you if it's `complete`, but it is a terminal function, you can't chain from it.

The above ask could also be handled by modifying `wiretap` to handle an `ExecResult` instead of a `Result`, but we'd have problems with method overriding and signatures trying to do that :-/

**Comment by michaelschlies** [comment]
Naively (and ignoring names and so on), would something along the lines of this sort of give you the best of both worlds? or (less ideally) branching in wiretap on `listener instanceof ExecResulut`
```
  default Promise<T> errtap(Action<ExecResult<T>> listener) {
    return transform(up -> down ->
      up.connect(down.onComplete(() -> {
        try {
          listener.execute(ExecResult.complete());
        } catch (Throwable e) {
          down.error(e);
        }
      }))
    );
  }
```
