### ISSUE TITLE
Migrate from javax.security.cert to java.security.cert

### ISSUE THREAD

**Issue by ldaley** [ratpack/ratpack#1599]

**Comment by johnrengelman** [comment]
The change in `SSLSession` to support this also drops the the use of `X509Certificate` for the generic `Certificate` class.
See: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLSession.html#getPeerCertificateChain() vs https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLSession.html#getPeerCertificates()

We have a couple options here:
1) Have `Request.getClientCertificate()` return `Optional<java.security.cert.X509Certificate>` and then do type casting in `NettyHandlerAdapter.userEventTriggered` to populate the certificate into channel attributes (this essentially changes the package names but doesn't change anything else).
2) Change `Request.getClientCertificate()` to return `Optional<java.security.cert.Certificate>` and rely on the developer to do any casting where needed.
3) Drop `Request.getClientCertificate()` and replace it with `javax.net.ssl.SSLSession Request.getSslSession()` giving the server access to the entire SSL session data, where they can access the certificates themselves and other details. This is what Vertx did in response to this change, see - https://github.com/eclipse-vertx/vert.x/pull/2078/files

I'm inclined to follow Vertx's lead here and just expose the entire `SSLSession` since it gives the developer more freedom and keeps us from potentially restricting access to data we do not forsee.
