### ISSUE TITLE
Runtime issues while running ratpack on jdk17 and guice-5.1.10 with certificates based request 

### ISSUE THREAD

**Issue by sindhushreem** [ratpack/ratpack#1654]
We are running the ratpack with jdk 17 .On the startevent we are seeing the nettyhandler exception stating the method is deprecated .
 ERROR ratpack.server.internal.NettyHandlerAdapter  -
java.lang.UnsupportedOperationException: This method is deprecated and marked for removal. Use the getPeerCertificates() method instead.

**Comment by sindhushreem** [comment]
We are seeing the nettyHandler exception for getting the certificates based request to ratpack on jdk 17 .

**Comment by johnrengelman** [comment]
This is due to the intentional degradation of the `javax.security.cert` package introduced in Java 15 - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8241047

This degradation forces a breaking API change in Ratpack to accommodate the new `java.security` package and classes and was introduce here - https://github.com/ratpack/ratpack/pull/1635
This change is available in `2.0.0-rc-1` and cannot be back-ported to the 1.x line as it is a breaking API change.
