### ISSUE TITLE
Add support for Slfj MDC support

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#551]
See MDC section of http://www.slf4j.org/manual.html

For us to support this, we'd need to manage swapping out thread bound MDCs as executions acquire a thread. This could be done quite easily with an ExecInterceptor implementation.

Somewhat dependent on #550

**Comment by davidmc24** [comment]
See also: http://www.slf4j.org/api/org/slf4j/MDC.html

This interceptor should:
* Maintain a `ConcurrentMap<Execution, Map<String, String>>`, where each value is a MDC context map
* Before running the continuation, check the internal map, and if an entry for the current execution is available, set it in the MDC; if not, clear the MDC
* Run the continuation
* After running the continuation, get the context map from the MDC.  If there was one, store it in the internal map.

Together, this means that, once the interceptor is registered, the user can directly use the SLF4J MDC API, and it will just work.

**Comment by alkemist** [comment]
Actually, `Execution` is a registry. We could just put the context map in there which removes the need for managing a concurrent map.

**Comment by zedar** [comment]
I'm about to finish implementation of MDCInterceptor, but I've got 2 questions:
1. I understand that the goal is to pass MDC entries between threads in the same execution. Then blocking, promise with execController.control.exec() should inherit MDC entries. But for example org.slf4j.helpers.BasicMDCAdapter uses InheritableThreadLocal, so entries are inherited between child threads by default. Log4j uses ThreadLocal when special property (isThreadContextMapInheritable) is not set else it uses InheritableThreadLocal too. If logging providers have similiar functionality, do we need this interceptor anyway?

2. In order to unit test MDC functionality, we need one of the logging providers on class path. Without it Slf4j uses NOPMDCAdapter. Slf4j tries to get MDCAdapter via org.slf4j.impl.StaticMDCBinder. Could you give me some hints? Should I add logging provider dependency for ratpack-core tests or should I provide custom stubs for StaticMDCBinder and MDCAdapter?

**Comment by davidmc24** [comment]
I think the key things that are different about Ratpack that require a different approach to handling the MDC are (please correct me if I'm wrong, @alkemist):

* The execution segments for an execution may be executed on unrelated threads in a pool (not child threads)
* On a given thread, you can't assume that the only work performed will be for a single execution until its completion

In terms of testing logging behaviors, my experience in the past has been that it's pretty much always easier and cleaner to use some form of Test Double rather than parsing log output for assertions.  I haven't done it with MDC before, but it looks to me like you should be able to set `MDC.mdcAdapter` in your `setup` block, and restore it in your `cleanup` block, without having to mess with `StaticMDCBinder`.

**Comment by zedar** [comment]
```MDC.mdcAdapter``` is intialized in  ```static``` section:

    static {
    try {
      mdcAdapter = StaticMDCBinder.SINGLETON.getMDCA();
    } catch (NoClassDefFoundError ncde) {
      mdcAdapter = new NOPMDCAdapter();
      ...

If ```StaticMDCBinder``` is not on classpath, ```NOPMDCAdapter``` is used (returns always null). If we do not add dependency to logger provider (log4j, ...) as testCompile, then, I think, we have to provide ```StaticMDCBinder``` implementation that returns stubbed ```MDCAdapter```.

**Comment by davidmc24** [comment]
My suggestion was to ignore how it's initialized, and then overwrite the value of the static field.

**Comment by zedar** [comment]
MDC has private constructur and no method to change static ```mdcAdapter``` field. So I think it is not possible to overwrite it. I will add some stubbing classes to simulate logging factory.

I've got another question. Once we start new execution, do you expect that MDC entries as passed from previous continuation (I mean from block "1")? 

    // 1
    MDC.put("value", "foo1")
    promise { f ->
      execController.control.exec().start {
        // 2
        values << MDC.get("value")
         f.success("foo1")
       }
     }

Correct me if I'm wrong but block "2" is not intercepted, so if logging factory uses ```ThreadLocal``` (like log4j in default configuration) and not ```InheritableThreadLocal``` (like java.util.logging) then block "2" will not see "value" in MDC context.

**Comment by davidmc24** [comment]
@zedar See below for an example of stubbing out `MDC.mdcAdapter`.  The key thing to realize is that Spock tests are written in Groovy, and Groovy allows access that Java wouldn't.

```groovy
package ratpack.logging

import org.slf4j.MDC
import org.slf4j.helpers.BasicMDCAdapter
import ratpack.exec.ExecControl
import ratpack.exec.ExecController
import ratpack.func.Action
import ratpack.test.exec.ExecHarness
import spock.lang.AutoCleanup
import spock.lang.Specification

import java.util.concurrent.CountDownLatch

class MDCExampleSpec extends Specification {
  def executionId = 1
  def origMdcAdapter
  def stubMdcAdapter = new RecordingMDCAdapter()

  @AutoCleanup
  ExecHarness harness = ExecHarness.harness()
  List<Object> events = []
  def latch = new CountDownLatch(1)

  def exec(Action<? super ExecControl> action) {
    exec(action, Action.noop())
  }

  def exec(Action<? super ExecControl> action, Action<? super Throwable> onError) {
    harness.exec().onError(onError).onComplete {
      events << "complete"
      latch.countDown()
    } start {
      action.execute(it.control)
    }
    latch.await()
  }

  def setup() {
    origMdcAdapter = MDC.MDCAdapter
    MDC.mdcAdapter = stubMdcAdapter
  }

  def cleanup() {
    MDC.mdcAdapter = origMdcAdapter
  }

  def "can use mock MDC adapter"() {
    when:
    exec { ExecControl it ->
      it.execution.add(String, "${executionId++}")
      it.promiseOf("jdoe").then {
        MDC.contextMap = ["user":it, "requestId":"12345"]
      }
      it.promiseOf("54321").then {
        MDC.put("requestId", it)
        MDC.remove("user")
        MDC.clear()
      }
    }

    then:
    stubMdcAdapter.changes == [
      "ratpack-compute-1-1:1: set [user:jdoe, requestId:12345]",
      "ratpack-compute-1-1:1: put requestId=54321",
      "ratpack-compute-1-1:1: remove user",
      "ratpack-compute-1-1:1: clear",
    ]
  }

  private static class RecordingMDCAdapter extends BasicMDCAdapter {
    final List<String> changes = []

    private static String getContext() {
      "${Thread.currentThread().name}:${ExecController.current().map { it.control.execution.get(String) }.orElse(null)}"
    }

    @Override
    void put(String key, String val) {
      changes.add("${context}: put ${key}=${val}")
      super.put(key, val)
    }

    @Override
    void remove(String key) {
      changes.add("${context}: remove ${key}")
      super.remove(key)
    }

    @Override
    void clear() {
      changes.add("${context}: clear")
      super.clear()
    }

    @Override
    void setContextMap(Map contextMap) {
      changes.add("${context}: set ${contextMap}")
      super.setContextMap(contextMap)
    }
  }
}
```

**Comment by davidmc24** [comment]
@zedar As for whether the MDC should carry over to new executions (or, for that matter, new threads, etc.), my gut feeling is "no".  @alkemist, please feel free to chime in.

Based on my previous comments, I don't believe that the behavior would change based on whether `InheritableThreadLocal` was used or not, as I don't believe that the threads are actually in a parent-child relationship.  Testing can prove whether that's correct or not, though.

**Comment by alkemist** [comment]
We should not assume any relationship between executions. Any forked executions have a completely separate MDC. If the user wants to carry stuff over, they need to do this explicitly/manually.

We can't use ThreadLocal and friends for any of this. 

@zedar why can't we use slf4j-simple for the unit tests?

**Comment by zedar** [comment]
@davidmc24 of course it is groovy with auto generated methods. Thank you.
@alkemist slf4j-simple by default use ```NOMDCAdapter```, so it always returns null for ```MDC.get()```. We have to overwrite MDC.mdcAdapter with for example ```BasicMDCAdapter``` implementation.

**Comment by alkemist** [comment]
@zedar are you unblocked now?

**Comment by zedar** [comment]
Yes. Will send pull request today. Thanks

W dniu wtorek, 24 lutego 2015 Luke Daley <notifications@github.com>
napisał(a):
