### ISSUE TITLE
Add method for resolving commonVersions from Ratpack

### ISSUE THREAD

**Issue by johnrengelman** [ratpack/ratpack#563]
For example, people using pac4j often add additional pac4j dependencies such as `pac4j-http` and these versions should sync with the version of pac4j in ratpack...or at least a helper method to get at that dependency. Perhaps something like:

```
depdencies {
  compile ratpack.dependency('pac4j', 'pac4j-http')
}
```

**Comment by alkemist** [comment]
I'm not sure this is going to be maintainable over time. I don't really want to privilege extensions that ship with the core unnecessarily. I fully understand the problem and benefit of what you're proposing, just a little cautious on the long term cost.

The approach I have used in the past is to rely on Gradle's `failOnVersionConflict()` behaviour.

**Comment by johnrengelman** [comment]
Hmmm, ok. I follow. I didn't look at this close enough. Didn't realize that the `depedency` method is resolving the ratpack version, not the pac4j version.

**Comment by davidmc24** [comment]
I like the idea of some way to make this a smoother experience, but I'm not sure how best to accomplish it.  I definitely don't want ratpack-gradle to need to have special knowledge of the arbitrary libraries that modules (including third-party ones we may never have heard of) to get this to work.  I was thinking that perhaps we could set up a `ServiceLoader`-backed service provider so that modules could make the appropriate artifact info available to the gradle plugin, but there's a chicken-and-the-egg issue there.  For the modules to make anything available to the gradle plugin, they'd need to be available at buildscript-resolve-time, which means that you aren't using `ratpack.dependency` to declare them there.

I think the best we can accomplish for now is going to be documenting the use of dependency resolve rules in the pac4j section.

**Comment by alkemist** [comment]
We've started to do this in the manual. See the Rx page.

**Comment by johnrengelman** [comment]
What about adding a method that generates the resolve rule?

**Comment by alkemist** [comment]
Not sure what you mean.

**Comment by johnrengelman** [comment]
so, normally, you would configure a rule that says use the same version as `pac4j-core`...could we just add a method on `RatpackDependencies` that creates that same rule, but provides a short syntax. So 

```
ratpack.version('pac4j-http', 'pac4j-core')
```

is synonymous with 
```
configurations.all {
  eachDependency { details ->
    ....
  }
}
```

Not sure this is totally possible. Just thinking.

**Comment by alkemist** [comment]
I think this is going to be overreach. This kind of problem plagues all systems and I think we have to leave it to the build system and developers to work it out. We can certainly provide advice in the manual, but I'm still not convinced on going further than that.

**Comment by johnrengelman** [comment]
Ok. We'll leave it up to the manual to document these versions.
