### ISSUE TITLE
Slim down ServerConfig

### ISSUE THREAD

**Issue by davidmc24** [ratpack/ratpack#567]
ServerConfig should only contain the minimal data needed to start the server.
Anything else should be broken out into separate objects in the registry.

To remove:

* [ ] `maxContentLength`
* [x] `timeResponses`
* [x] compression stuff
* [x] `indexFiles`
* [x] `other`
* [ ] ~~`publicAddress`~~

**Comment by alkemist** [comment]
Here's some “info” here…

* `maxContentLength` can go when we move to not loading the request body eagerly, as we can then supply this value in handler land. We can probably push the default to the server registry.
* `timeResponses` - this can go, if we can simulate what it does. It has to be able to time from very early in our request handling (i.e. it has to count all the work NettyHandlerAdapter) does - this is used for our perf tests
* All the compression stuff can go to the registry, we'll have to rework asset serving to push this stuff from handler land back to Netty (i.e. response transmitter) instead of circumventing handler land
* indexFiles can go, will be part of the new asset handler API
* `other` can die a horrible death - can't wait to see this go
* `publicAddress` could go, we don't need this at startup

Doesn't leave a lot, which is great.

**Comment by davidmc24** [comment]
`other` is already dead.

**Comment by davidmc24** [comment]
Looked at it a bit more.  I think I'm in favor of leaving `publicAddress` in `ServerConfig`.  While it isn't strictly speaking needed for server construction, it's still a configuration setting that users will tend to think of as being server-level most of the time.

**Comment by alkemist** [comment]
@davidmc24 I think you're right.
