### ISSUE TITLE
Registry caching means prototypical providers are treated as singletons

### ISSUE THREAD

**Issue by robfletcher** [ratpack/ratpack#606]
Methods annotated `@Provides` that should be prototypical are treated as singletons due to registry caching. This means that, for example, the result of a provider method that acquires a database connections from a pool will get cached and then potentially used after it has been returned to the pool.

**Comment by alkemist** [comment]
Rough plan…

1. take `RegistryEntry` public (maybe make it implement `Provider`)
2. add some methods to `Registry` for exposing the entries
3. Change all the searching methods of `Registry` to apply the predicate to the type rather than instance
4. Change the caching layers to cache the entries, instead of instances

If anyone wants to get intimate with the registry, this would be a good ticket.

**Comment by alkemist** [comment]
Fixed in .15.
