### ISSUE TITLE
Improve and simplify base dir configuration

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#618]
## Rationale

The base dir is the effective file system root for the application. All relative paths (e.g. paths to templates, assets) are resolved relative to the base dir. This makes the application more portable.
Currently, how the base dir is found/specified is convoluted and inconsistent. We can do better.

## Approach

The conventional approach for finding the base dir will be to search the _classpath_ for a `.ratpack` marker file. It will also be possible to specify an alternative marker file name, as well as provide an arbitrary `Path` object to use as the base. The application should generally not really on the JVM working directory as this is hard to make consistent across the build, IDE and deployment.

At build time, this will require `src/ratpack` being placed on the classpath and a `.ratpack` file to be present. This isn't too different to the current setup, except that the .ratpack file will now be _required_.

## Implications 

The `ServerConfig` building API will need to change to support this approach.

Changes will be made to ensure that the `src/ratpack` directory is on the classpath in all scenarios (build run, build test, IDE run, IDE test, supported deployment modes).

**Comment by alkemist** [comment]
@ratpack/committers anyone want to pick this one up?

**Comment by rhart** [comment]
@alkemist is there any more to do on this?

**Comment by alkemist** [comment]
Just docs really, I think.

**Comment by garretwilson** [comment]
This will all become much clearer to me once I start going through the source code in an IDE, but I just want to note that if one is solely going from the documentation, it would appear from [23 Building with Gradle § 23.5 The base dir](https://ratpack.io/manual/current/gradle.html#the_base_dir) that setting `ratpack.baseDir` in the `build.gradle` file will set the base directory:

```
ratpack.baseDir = file('ratpack')
```

The confusion seems to be that "base dir" is being used in two slightly different senses in [23.5 The base dir](https://ratpack.io/manual/current/gradle.html#the_base_dir) and in [4.1.1.1 Base dir](https://ratpack.io/manual/current/launching.html#base_dir).

After experimentation it seems that `ratpack.baseDir` does not set the "base directory" that section [4.1.1.1 Base dir](https://ratpack.io/manual/current/launching.html#base_dir) talks about. Rather, it changes the default `src/ratpack` extra resource directory that is included (with the Ratpack Gradle plugin) to some other directory of your choosing.

So for example I could specify in `build.gradle`:

```
ratpack.baseDir = file("src/foobar")
```

Confusingly _this would not set the base dir_!! One would still need to place a `.ratpack` marker file inside `src/foobar` and do something like:

```java
.serverConfig(c -> c.baseDir(BaseDir.find()).build())
```

Thus perhaps `ratpack.baseDir` might be more aptly named something like `ratpack.resourcesDir`, because it apparently just specifies which extra directory gets added to the [`resources.srcDirs` source set of the Java Plugin](https://docs.gradle.org/current/userguide/java_plugin.html#source_sets).

So I don't need help getting things working now, I just wanted to point out that the documentation as currently written could be confusing for a beginner. I'll be happy to volunteer to help improve the documentation in the future if you'd like. 😉 Cheers.

**Comment by garretwilson** [comment]
The other thing that the documentation doesn't make clear is that if content is served from the base resource directory (e.g. `src/ratpack`), the `.ratpack` marker file is accessible by the HTTP client (i.e. it can be downloaded by the user)! While not exactly a security risk, it exposes a marker asset which is an implementation detail, not content.

To get around this, some subdirectory should be specified in the chain, e.g.:

```
.files(files->files.dir("subdirectory").indexFiles("index.html")
```
O'Reilly's _Learning Ratpack_ (p. 133) refers to such a `"static"` subdirectory, and the [Ratpack documentation](https://ratpack.io/manual/current/static-assets.html#from_a_directory_) uses a `"public"` subdirectory in the example. The problem is that neither documentation explicitly states that using such a subdirectory _is necessary_ if one wants to avoid exposing the `.ratpack` marker file to the client.

I'll of course be happy to help improve the documentation in this area as well if you like.

(I'll bet that if we discussed it some more we might even discover a better approach than a marker file for specifying the base directory.)

All the best.

**Comment by michaelschlies** [comment]
@garretwilson, I think if there is a documentation issue that is better suited as a new issue. Might I encourage you to open an issue on it and I will go ahead and plan on making some documentation updates next week to help clarify this point?

**Comment by garretwilson** [comment]
Sure! I'm a little busy for the next 24 hours, but I wanted to jot this down while I was thinking about it, and it was related to this ticket. I'll try to open a new ticket in a couple of days. Feel free to ping me if you don't hear from me.

**Comment by garretwilson** [comment]
Hi, @michaelschlies . Sorry for the delay, but as you've requested I've opened two issues #1449 and #1450 discussing the points I raised. All the best.
