### ISSUE TITLE
OSGi support

### ISSUE THREAD

**Issue by almibe** [ratpack/ratpack#669]
Hey all.  Has the topic of adding OSGi support to ratpack come up before?  I didn't check all of ratpack's dependencies, but the ones that I did check (over half and including netty) all had OSGi metadata in their manifests.  If there is interest in supporting OSGi I'd be willing to spend some time working on the issue.

Edit: By adding OSGi support I just mean adding OSGi metadata to the manifests at build time.  There are (at least) two common ways to do this with gradle.

**Comment by alkemist** [comment]
It hasn't come up. We should support it unless it's very onerous. I don't really know what's involved.

**Comment by almibe** [comment]
I should be able to test out adding OSGi metadata at build time this week.  It's usually trivial for libraries since you normally just want to export everything and don't want to take an active role in the lifecycle of the OSGi bundle.  The best case scenario is a one liner (https://github.com/TomasMikula/EasyBind/commit/409202070c279956f22ea83c8fb46db87575231f).  I'm not sure if the groovy extension classes in core will still work or not but other than that I don't see any issues.

**Comment by almibe** [comment]
I was testing this out and I ran into an issue since one of ratpack's dependencies isn't an OSGi bundle, netty-transport-native-epoll-4.1.0.Beta4-linux-x86_64.  Which is weird since all the other netty jars have the OSGi metadata in them.  Since when it comes to library dependencies OSGi is all or nothing without a bunch of hacks, for the time being adding OSGi support to ratpack isn't possible without ugly workarounds.  I'm going to put this on the back burner (and for now just put the workaround hacks in my build script) so feel free to either leave this issue open or close it as you see fit.

**Comment by almibe** [comment]
Actually after thinking this over some more I think I'm going to go ahead and make a pull request with OSGi support added to the gradle builds for the core and pac4j subprojects.  I think even with the issue mentioned above it is worthwhile to have the OSGi metadata in place since it will make the workarounds I mentioned simpler and when the netty issue is resolved we'll be good to go.

I couldn't find a good way to add OSGi support to all of the subprojects so I think doing it on a case by case basis is the way to go.  I'm currently only using ratpack-core in my application, but I plan on using the pac4j project eventually and it looks like all the pac4j stuff is already packaged as OSGi bundles on their side.

**Comment by stevengssns** [comment]
Hi,

has anyone had another look at providing OSGi support?

In any case I decided to try it out while learning more about Ratpack. And to my own surprise I actually got something up and running without all that many issues to overcome (I don't seem to have run into the Netty issue that was mentioned, but maybe that's just because of my setup. I'm using version 4.1.0.Beta8) . 
I successfully tried out some examples from the manual that depend on the ratpack-core, ratpack-guice and ratpack-rx modules.

Currently I'm going to go through the other (relevant) modules to try and get them running in the OSGi container. But even if one of those has one or more dependencies which don't provide OSGi support, there is no reason not to generate the OSGi metadata, as they might provide it in the future. Or if it is an optional dependency, it can be marked as such in the metadata..
 
If I haven't given up after that, I'll be having a look at testing. Ideally there should be some tests that run the code inside an OSGi container. 
It's not because all of the dependencies become "active" inside the OSGi container, that they are actually also working. If a bundle (a jar file that with OSGi metadata) is playing around with class loaders, the it is likely to be broken.. 

So still lots of work to be done (if it hasn't been done already or course...)
If I ever get through the list of modules I might already share my code (the gradle config changes) and findings on that.

I already have one question regarding an issue that I stumbled upon when getting the ratpack-core module running in the OSGi container.
Apparently `ratpack.server.internal.BaseDirFinder` is depending on `com.sun.nio.zipfs.ZipFileSystemProvider`, which is alway a nasty issue when using OSGi, as it does not expose implementation specific packages by default. 
Are you aware of this dependency?


Possible fixes (from an OSGi perspective):

1. Obviously you should try to get rid of this kind of dependency. I assume you know that Java 9 is going to be hiding internal packages too. Though maybe this is a dependency for which they will be providing a solution?  

2. If this functionality might not be needed by everyone, then the package should be made optional, which is what I did. The OSGi runtime will look for a bundle that is exporting this package, but if it can't find it, it will not prevent the bundle from starting. 

   ```gradle
   jar {
     manifest {
       instruction 'Import-Package', 'com.sun.nio.zipfs.*;resolution:=optional', '*'
     }
   }
   ```

   Needless to say that any code path that does try to use any class from this package will result in a ClassNotFound exception.

3. If the package is really needed (either because someone wants to use it, or because it is a critical dependency), then you will probably end up adding it to the boot class path (and you won't be having a good day...).

**Comment by michaelschlies** [comment]
On the plus side, this dependency is even worse than it was a 21 months ago!
The internal API in question (ZipFileSystemProvider) has since been relocated from the JDK per jdeps below:
```
   ratpack.server.internal.BaseDirFinder              -> com.sun.nio.zipfs.ZipFileSystemProvider            JDK internal API (JDK removed internal API)
```
However, a new location within the jdk.zipfs platform module fills that need:
```
~$ java --describe-module jdk.zipfs
jdk.zipfs@9
requires java.base mandated
provides java.nio.file.spi.FileSystemProvider with jdk.nio.zipfs.ZipFileSystemProvider
contains jdk.nio.zipfs
```

Also this is the current show stopper to issue #1221
