### ISSUE TITLE
Disappearance of `findBaseDirProps`

### ISSUE THREAD

**Issue by yterradas** [ratpack/ratpack#673]
hi, 
it seems that the publication of version 0.9.16 removed `ServerConfig.findBaseDirProps`, also ratpack-config is the only 0.9.15 versioned jar.  were those changes intentional?  where can i find the changes made with each release?  thank you for your work, and in advance for providing answers to my question.

**Comment by rhart** [comment]
Each release has a release note which can be found here https://github.com/ratpack/ratpack/releases.  

Each release also has a milestone which you can use to see all the issues closed as part of that release e.g. https://github.com/ratpack/ratpack/issues?q=milestone%3Arelease-0.9.16

`ServerConfig.findBaseDirProps` has gone in favour of `ServerConfig.findBaseDir`.  This is because we no longer look for `ratpack.properties` to determine the base directory.  You can see the change here https://github.com/ratpack/ratpack/commit/1e789769a6da097d9dcbc0bade8dcb2434c3470a

Also, `ratpack-config` has been merged to `ratpack-core`.  This change is in flight, see #617 

HTH

**Comment by alkemist** [comment]
I've just pushed some docs explaining how it now works.

http://ratpack.io/manual/0.9.17/launching.html#base_dir

That also applies to .16.

**Comment by yterradas** [comment]
thank you @rhart @alkemist
