### ISSUE TITLE
Snapshots not making it to jcenter?

### ISSUE THREAD

**Issue by dsyer** [ratpack/ratpack#701]
Issue #14 says this should be happening, and I can see some snapshots at http://oss.jfrog.org/repo/io/ratpack/ratpack-core/, but nothing for a few days. Is that a known issue? Am I looking in the wrong place?

**Comment by danhyun** [comment]
Everything seems to be there?

Here's the Spring work we've been doing http://oss.jfrog.org/repo/io/ratpack/ratpack-spring-boot/0.9.18-SNAPSHOT/

And for `ratpack-core` you can see latest entry

> ratpack-core-0.9.18-20150612.051446-11.jar               12-Jun-2015 05:17  626.16 KB

Are you referring to the directory timestamps?

> 0.9.18-SNAPSHOT/          02-Jun-2015 00:58    -

Seems to suggest no new entries since the 2015/6/2 but they are there.

**Comment by dsyer** [comment]
OK. I didn't notice the new jars (was looking at directories). Thanks.
