### ISSUE TITLE
Return 415 rather than 500 for unsupported media types

### ISSUE THREAD

**Issue by mirkonasato** [ratpack/ratpack#794]
Given a Handler that uses `context.parse()`, POSTing a request with an unsupported Content-Type returns _500 Internal Server Error_

    ratpack.parse.NoSuchParserException: Could not find parser able to produce object of type ... from request of content type 'text/plain'
      	at ratpack.handling.internal.DefaultContext.lambda$parse$183(DefaultContext.java:302)
	at ratpack.handling.internal.DefaultContext$$Lambda$142/766007230.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at ratpack.handling.internal.DefaultContext.parse(DefaultContext.java:302)

Returning _415 Unsupported Media Type_ response would be more appropriate.

**Comment by alkemist** [comment]
I remember thinking about this at the time, but didn't quite come to a conclusion.

I think you're right, this would be better, but it's not entirely clear cut. We don't know for certain that the request would have succeeded had the content type been different. A parser may choose to pass on the request for any reason, based on the API contract.

For cases where the endpoint does really support multiple content types, the intent (from my side) is that authors use the `Context.byContent` construct, which does issue a 415 on no match.

**Comment by mirkonasato** [comment]
I've only recently started using Ratpack so it's quite possible that I don't fully understand how it's supposed to be used.

Let's say I just want to receive a JSON object, parse it, save it somewhere, and return 204. If the client sends a different Content-Type I don't want my service to fail with a 500 because it's not a server error, it's a client error. What's the best way to do that?

From the [manual](http://ratpack.io/manual/current/jackson.html#reading_json_requests) `Context.parse()` seemed exactly what I needed. But apparently I would have to catch `NoSuchParserException` and return 415 myself or something like that. That's surprising.

`Context.byContent` looks at the Accept header so it seems a different thing.

**Comment by erdi** [comment]
@mirkonasato Yes, you are right `Context.byContent()` deals with `Accept` header and not with `Content-Type` header. Luke probably meant to point you at [`Handlers.contentTypes()`](http://ratpack.io/manual/current/api/ratpack/handling/Handlers.html#contentTypes-java.lang.String...-).

It's not feasible to return a 415 instead of throwing `NoSuchParserException` when there isn't any parser that's capable of parsing a given request. `Context.parse()` iterates over all `Parser` implementations in the registry and asks each one of them if they are capable of performing the parsing. Each one of them can either return null (not cable of parsing given request) or a non null value (as per the contract in javadocs for [`Parser.parse()`](http://ratpack.io/manual/current/api/ratpack/parse/Parser.html#parse-ratpack.handling.Context-ratpack.http.TypedData-ratpack.parse.Parse-)). Now, imagine that there was a parser registered that can parse `text/plain` into and only into `Foo` but you called `Context.parse(Bar)` for a request that contained `text/plain`. You clearly wouldn't want to return a 415 in such situation, would you? 

As Luke wrote: 
> "A parser may choose to pass on the request for any reason, based on the API contract."

and pass on here means to return null from `Parser.parse()`

**Comment by alkemist** [comment]
You're right, I had a brain meltdown in mentioning byContent.

For the time being, what I'd do is write your own Parser implementation with this logic. You can compose parsers fairly easily by calling one of the ctx.parse methods from inside your parser.

**Comment by erdi** [comment]
Sorry for pointing it out but you probably suffered another meltdown;). 

Firstly composing parsers by using `Context.parse()` will not fly because it returns `Promise<T>` while `Parser.parse()` has to return `T`. Secondly your comment was to probably to provide a workaround for #793 and not this issue which is about what should happen when no parsers capable of parsing the request are found. Thirdly, even if composition via `Context.parse()` was possible then you would still achieve nothing because `JsonParser` will not parse the request with a content type that is considered non-json by it anyway and as far as I know there is no easy way to teak the content type of a request in the context.

**Comment by alkemist** [comment]
Parsers can invoke other parsers via: http://ratpack.io/manual/current/api/ratpack/handling/Context.html#parse-ratpack.http.TypedData-ratpack.parse.Parse-

You're right, I was talking about #793. Moving to there…

**Comment by erdi** [comment]
Oh, good to know.

**Comment by alkemist** [comment]
No I'm not…

I'm thinking that the Jackson parser should use a stategy object from the context to determine if the request is JSON or not. Something like…

```
interface IsJsonPredicate {
  boolean test(Context ctx)
}
```

We'd put a default impl in the registry that returned `true` for `application/json` and `*+json`. If you have custom mime types you'd just bind your own impl of this.

@mirkonasato WDYT?

**Comment by erdi** [comment]
+1

**Comment by mirkonasato** [comment]
Sounds good to me.

**Comment by alkemist** [comment]
I'm going to close this one off. I'm going to hold off on adding the `IsJsonPredicate` thing until we have more evidence that it's actually needed, now that we detect `+json` types.
