### ISSUE TITLE
'Connection: Close' directive is not being respected

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#817]
This should possibly work by closing the connection if the header `Connection: Close` is set on the response during request processing. We could possibly sugar this by adding a `forceConnectionClose()` method to response that just adds this header.

**Comment by brucenunk** [comment]
I think there are two issues here @alkemist. Firstly, DefaultResponseTransmitter setting the "Connection" header regardless of whether it has already been set and secondly, an option to explicitly close the connection once the response has been committed.

The first issue would have zero change to the api, just a check in "pre" to see whether the header has already been set and falling back to existing logic if not (https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/server/internal/DefaultResponseTransmitter.java#L83-L85). Then in "post" check whether "Connection" header is keep-alive otherwise close (https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/server/internal/DefaultResponseTransmitter.java#L234-L236) so I'm quite happy to pick that work up now.

The second issue would involve a change to both Response and ResponseTransmitter apis and I'm not sure whether you want to commit to that for 1.1.0 release?

James.

**Comment by alkemist** [comment]
I'd change that slightly,

I'd set `isKeepAlive` in `pre()` based on the logic you describe. Then, no other methods need to be updated.

BTW, `ResponseTransmitter` is internal so there's no problem changing any of that API.

**Comment by brucenunk** [comment]
OK no worries, will do that. Having a few issues with Intellij at the minute but will get to it this alvo.

**Comment by alkemist** [comment]
Great :)

If we can help with the IDEA stuff holler.

**Comment by brucenunk** [comment]
Hollering ;) I've had it running in Intellij before so no idea what it's boggle is.

I've imported the ratpack.gradle file and getting this:

Error:Can't register given path of type 'SOURCE' because it's out of content root.
Content root: '/home/jamesl/dev/github/ratpack/buildSrc'
Given path: '/home/jamesl/dev/github/ratpack/ratpack-gradle/src/main/groovy'

I've since added it (as far as I can tell), refreshed the project and still the same.

I've also tried ./gradlew idea then importing the ratpack.ipr file but that gives me issues too.
 Any ideas?

**Comment by brucenunk** [comment]
OK I've got the project imported but it's not a gradle-linked project ... I'll deal with it.

Just added a test to DefaultReponseSpec (looked like the right place) but it passed without me making any changes. After a bit of tracing through the code it appears the DefaultHttpClient sets a "Connection: close" request header so I can't get a failing test (https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/http/client/internal/RequestActionSupport.java#L213) (should have known this as I was in there last week).

I can make the change and commit it though if you're ok with that?

**Comment by alkemist** [comment]
Import won't work.

You have to run ./gradlew idea and then open the .ipr file.

**Comment by alkemist** [comment]
Sure thing. Push the change and I'll work out how to test it.

**Comment by alkemist** [comment]
@brucenunk I added a method to response and improved the tests: https://github.com/ratpack/ratpack/commit/95f996600e880e77b5941bf539934734eda1bea2#diff-6e5c198bdb05649ed40ad49f7b376001R276

I'm not keen on adding a server config option because you can very easily simulate this by putting a handler at the start of your pipeline that calls this method.

```
handlers {
  all { response.forceCloseConnection(); next() }
  …
}
```

The less config options the better.

Thanks again for the contribution.
