### ISSUE TITLE
Multiple handlers with different http methods and the same path spec doesn't work

### ISSUE THREAD

**Issue by timic** [ratpack/ratpack#847]
For example, consider the following groovy chain:
```groovy
handlers {
    get "test", {
        response.status(200).send("GET - OK")
    }
    post "test", {
        response.status(200).send("POST - OK")
    }
}
```
Let's test it with curl:
```
$ curl -XGET http://localhost:5050/test; echo
GET - OK
```
So `GET ` method works well. But `POST` doesn't:
```
$ curl -XPOST http://localhost:5050/test; echo
Client error 405
```
Server log also contains an error:
```
[ratpack-compute-29-1] ERROR ratpack.error.internal.DefaultDevelopmentErrorHandler - 405 client error for request to /test
```
I assume that this is a bug. And it don't give a chance to implement any RESTful API.

**Comment by rhart** [comment]
This is by design, see http://ratpack.io/manual/current/api/ratpack/handling/Chain.html. Specifically the "HTTP Method binding" section

What you need to use is `Context#byMethod`, see here for details http://ratpack.io/manual/current/api/ratpack/handling/Context.html#byMethod-ratpack.func.Action-

If you can't get this to work ping us a message on the forum or slack channel and I'll be happy to help further

**Comment by timic** [comment]
@rhart Thanks. This works well:

```groovy
handlers {
    path("test") {
        byMethod {
            get {
                response.status(200).send("GET - OK")
            }
            post {
                response.status(200).send("POST - OK")
            }
        }
    }
}
```

I think this should be mentioned in manual.
