### ISSUE TITLE
Add support for HttpClient request/response interceptors

### ISSUE THREAD

**Issue by hyleung** [ratpack/ratpack#975]
Ref: https://github.com/ratpack/ratpack/issues/913#issuecomment-214787835 (Zipkin integration)

As far as I can tell, there currently aren't any "hooks" that allow interception of `HttpClient` requests and responses. On the response end of things, I believe it's possible to use [`Promise.wiretap`](https://ratpack.io/manual/current/api/ratpack/exec/Promise.html#wiretap-ratpack.func.Action-) to intercept the response. Don't believe there's a straightforward way to do this for the request.

In my specific scenario, this would make logging of Zipkin client spans easier, but could be more generally useful.

**Comment by hyleung** [comment]
Would it be possible to look for interceptors via the registry? Something like this: https://github.com/hyleung/ratpack/commit/80b6ba1050332b23215927eac42b5837b14fbcc3 (wanted to write the corresponding unit tests to verify it, but couldn't quite figure out how to add entries into the registry in the test setup).

**Comment by rhart** [comment]
That's what I was thinking too.  You can see test examples in the health check code https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/test/groovy/ratpack/health/HealthCheckHandlerSpec.groovy#L102

**Comment by johnrengelman** [comment]
While implementing retrofit integration (https://github.com/ratpack/ratpack/pull/976), I've also realized that interceptors would extremely helpful.
The issue here is if we abstract away the `HttpClient` then we need a way to configure per request type behavior.
My use case was that I wanted to add a specific header to every outgoing request for auth.
Using a Retrofit interface, I could do this, but then would have to declare each and every item like this as part of the API interface.

It would greatly simplifying things if I could globally configure this type of behavior.

Technically speaking, I don't think this would be difficult to implement, but there are some areas around usability that we want to be mindful of.

For example, there is only 1 `HttpClient` registered in the app, so any interceptors would be global. This means, it would be the developer's responsibility to handle any conditional logic (i.e. add a header to requests going to foo.com but not bar.com).
An alternative might be to add an API that does a type of "shallow" clone of `HttpClient` that interceptors could be added to. Then the interceptors are applied only when calling through the "clone".

**Comment by hyleung** [comment]
@johnrengelman oh ic. So, I guess in your case, you would want to actually be able to mutate the outbound request (e.g. add a header). Originally (because I was only thinking of using it for tracing/logging), I was going to make it an immutable copy of the request but I suppose that would make it much less useful more generally.

Re. the per-request interceptors - what about getting some sort of HttpClient factory from the context that will build a sort of customized HttpClient?

**Comment by hyleung** [comment]
@rhart yeah I thought that `binding { }` block would work too, but for some reason I think I'm getting two different instances of the `Execution` in the test and the code-under-test. Could be a poorly written test on my part - this fixture is a little different, too in that it extends `HttpClientSpec`, which adds an `otherApp`. Also I'm seeing the `ChannelFuture` listener get an extra callback when I added an log statement  (https://github.com/hyleung/ratpack/commit/af7c23d5b17ee98196d8068240fe5726b5b8f8b1#diff-e662b0483aa40966d5f691b3835ca23cR211) - not really sure what to make of it.

E.g. executing _"can make simple get request"_ in `HttpClientSmokeSpec`:
```
2016-05-03 20:32:34,329 INFO r.s.RatpackServer [main] Starting server... 
2016-05-03 20:32:35,219 INFO r.s.RatpackServer [main] Building registry... 
2016-05-03 20:32:36,538 INFO r.s.RatpackServer [main] Ratpack started for http://localhost:55473 
2016-05-03 20:32:36,716 INFO r.h.c.i.RequestActionSupport [ratpack-compute-4-1] Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET  HTTP/1.1 
2016-05-03 20:32:36,850 INFO r.s.RatpackServer [ratpack-compute-1-2] Starting server... 
2016-05-03 20:32:36,862 INFO r.s.RatpackServer [ratpack-compute-1-2] Building registry... 
2016-05-03 20:32:36,878 INFO r.s.RatpackServer [ratpack-compute-1-2] Ratpack started (development) for http://localhost:55475 
2016-05-03 20:32:36,926 INFO r.h.c.i.RequestActionSupport [ratpack-compute-1-2] Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /foo HTTP/1.1 
2016-05-03 20:32:37,066 INFO r.s.RatpackServer [main] Stopping server... 
2016-05-03 20:32:37,073 INFO r.s.RatpackServer [main] Server stopped. 
2016-05-03 20:32:37,073 INFO r.s.RatpackServer [main] Stopping server... 
2016-05-03 20:32:37,076 INFO r.s.RatpackServer [main] Server stopped. 
```

**Comment by alkemist** [comment]
Thanks for your patience on this. We'll tackle this for the next release, 1.5.

**Comment by johnrengelman** [comment]
This was added in https://github.com/ratpack/ratpack/commit/b9bd8cf1807d5b12d5b389438813f485615f0e13

**Comment by ldaley** [comment]
I'm just reopening this as a reminder to myself to review before shipping 1.6.
