### ISSUE TITLE
Memory leak from HystrixThreadPoolMetricBroadcaster/ConcurrentLinkedDeque

### ISSUE THREAD

**Issue by adamkeyser** [ratpack/ratpack#993]
Our team uses the Hystrix integration, but until recently we did not use the live monitoring Hystrix provides. We recently implemented turbine, and after doing so we start to see "out of memory: heap space" for our Ratpack instances. It takes a couple hours running to reproduce, and it doesn't always seem to occur.

After taking a look at the dumps - it appears that there is some kind of circular reference causing a build up of items in a ConcurrentLinkedDeque. An image of the buildup can be found here : http://imgur.com/F4B2J00

In the image link above, you can see we had 61,000,000 nodes in a ConcurrentLinkedDeque. The issue only seems to happen if turbine is listening to the Hystrix streams (we're currently verifying).

I'm happy to provide any additional information, but the hprof is 1.5 gigs. If there's any way I can help diagnose let me know. This is on Ratpack 1.2.0

**Comment by rhart** [comment]
I wonder if turbine keeps reinitiating the stream and the previous subscription is not getting cancelled.  So we get a build up of subscribers in `HystrixThreadPoolMetricsBroadcaster`.

I need to dig in a bit more.  Will get back to you soon as poss.

**Comment by rhart** [comment]
I'm pretty sure that's it.  If I just keep hitting `localhost:5050/hystrix.stream` in a browser I can see the `bufferedSubscribers` count just increasing all the time.

I need to try and reproduce in a test and then work on a fix

**Comment by adamkeyser** [comment]
Great news! Was somewhat worried it may be hard to reproduce. Thanks for looking into this so quickly.

**Comment by rhart** [comment]
Thanks for reporting it!

Hopefully reproducing in a proper test won't take too long.

**Comment by rhart** [comment]
I think the problem lies in `FanOutPublisher`.  
Simplistically, we go `PeriodicPublisher -> MulticastPublisher -> Buffer -> Fanout -> ResponseTransmitter` 
Fanout converts from a list to individual metrics and calls the onNext of ResponseTransmitter.
ResponseTransmitter requests 1 item from upstream, receives 1, checks the state of the channel and cancels the subscription if it's not open, or writes to the channel and requests another item.
The problem occurs, I think, when an empty collection is sent to Fanout.  It will not call the onNext of the downstream subscriber and therefore the channel state is never checked and no more items are ever requested from upstream.  
But PeriodicPublisher keeps publishing and everything backs up in the buffer.
I think the fix is to check if the Iterable has an item at all first thing in the `FanOutPublisher#onNext` and if not request more from upstream.  This is safe to do because the downstream subscriber has requested 1 that it never got so the demand is still there.

I just need time to confirm, test and fix.  But from investigation this seems likely what happens in the case I reproduced with the browser.  You might be able to test the theory by implementing your own `HystrixMetricsEventStreamHandler` and stripping out the threadpool and collapser metrics if you don't use them, I assume commandMetrics always produces something.  This means you will also not have to wait for a new release.

If you fancy getting your hands dirty with some reactive streams though and send a PR then this is a good chance ;)
